# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hornect' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hornect
  pod "Parse/UI"
  pod "AlamofireImage"

  target 'HornectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HornectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
